function eq = calculate_equilibrium(alpha, beta, m, w, s, muM, muR, c, theta, pc, G, e0, gamma)
%CALCULATE_EQUILIBRIUM  Closed-form equilibria for the two-stage biform game.
%   All inputs are scalars OR element-wise compatible arrays (grids from
%   meshgrid). All outputs have the same shape as the broadcast inputs.
%
%   Returns a struct eq with fields:
%       pM_N, pR_N          Non-cooperative collection prices
%       qM_N, qR_N          Non-cooperative collection quantities
%       k_N                 Non-cooperative conversion rate
%       Pi_M_N, Pi_R_N      Non-cooperative profits
%       pM_C, pR_C          Biform (cooperative) collection prices
%       qM_C, qR_C          Biform collection quantities
%       k_C, n_C            Biform conversion rate, R&D sharing proportion
%       phi_M, phi_R        Biform Shapley profit allocations

% ---------- 1. Non-cooperative game ----------
N_M_N = c.^2.*(2*alpha.^2.*(s - w - muM) - alpha.*beta.*(m + muR + e0.*pc - s) + beta.^2.*(m + e0.*pc - w)) ...
      + c.*( alpha.^3.*(gamma.^2.*pc.^2.*(muM - s + w) + gamma.*pc.*theta.*(2*muM - muR - s + 2*w - m) - theta.^2.*(m - muM + muR - w) - e0.*pc.*theta.*(gamma.*pc + theta)) ...
      + alpha.^2.*beta.*(2*gamma.^2.*pc.^2.*(-muM + s - w) + gamma.*pc.*theta.*(3*m - 2*muM + 2*muR - 3*w) + theta.^2.*(m - w) + e0.*pc.*theta.*(3*gamma.*pc + theta)) ...
      + alpha.*beta.^2.*(gamma.^2.*pc.^2.*(muM - s + w) + gamma.*pc.*theta.*(-muR + s + 2*w - 3*m) - theta.^2.*(m + muR - s) - e0.*pc.*theta.*(3*gamma.*pc + theta)) ...
      + beta.^3.*(gamma.*pc.*theta.*(m - w) + theta.^2.*(m - w) + e0.*pc.*theta.*(gamma.*pc + theta)) );

N_R_N = c.^2.*(2*alpha.^2.*(s - m - muR - e0.*pc) + alpha.*beta.*(2*m - muM + s - 3*w + 2*e0.*pc)) ...
      + c.*( alpha.^3.*(2*e0.*gamma.*pc.^2.*theta + gamma.^2.*pc.^2.*(-muM + s - w) + gamma.*pc.*theta.*(2*m - muM + 2*muR - s - w)) ...
      + alpha.^2.*beta.*(-2*e0.*pc.*theta.*(2*gamma.*pc + theta) + 2*gamma.^2.*pc.^2.*(muM - s + w) + gamma.*pc.*theta.*(2*muM - 2*muR - 4*m + 4*w) - theta.^2.*(2*m - muM + 2*muR - s - w)) ...
      + alpha.*beta.^2.*(2*e0.*pc.*theta.*(gamma.*pc + theta) + gamma.^2.*pc.^2.*(-muM + s - w) + gamma.*pc.*theta.*(-muM + s + 2*m - 3*w) + 2*theta.^2.*(m - w)) );

D = alpha.^4.*gamma.*pc.*theta.*(gamma.*pc + theta).^2 ...
    + alpha.^3.*(-2*beta.*gamma.*pc.*theta.*(gamma.*pc + theta).^2 - beta.*theta.^4 - 2*c.*(gamma.*pc + theta).^2 - 4*c.*gamma.*pc.*theta - beta.*gamma.*pc.*theta.^3) ...
    + alpha.^2.*(3*beta.*c.*(gamma.*pc + theta).^2 + 4*c.^2) + alpha.*beta.^2.*c.*theta.*(4*gamma.*pc + theta) ...
    + 2*alpha.*beta.^3.*gamma.*pc.*theta.*(gamma.*pc + theta).^2 + alpha.*beta.^3.*theta.^4 + alpha.*beta.^3.*gamma.*pc.*theta.^3 ...
    - beta.^4.*gamma.*pc.*theta.*(gamma.*pc + theta).^2 - beta.^3.*c.*(gamma.*pc + theta).^2 - beta.^2.*c.^2;

eq.pM_N = N_M_N ./ D;
eq.pR_N = N_R_N ./ D;

eq.qM_N = alpha.*eq.pM_N - beta.*eq.pR_N;
eq.qR_N = alpha.*eq.pR_N - beta.*eq.pM_N;
eq.k_N  = (theta.*(alpha.*eq.pR_N - beta.*eq.pM_N) + pc.*gamma.*(alpha - beta).*(eq.pM_N + eq.pR_N)) ./ c;

eq.Pi_M_N = (theta.*eq.k_N - eq.pM_N - w - muM + s).*eq.qM_N;
eq.Pi_R_N = (theta.*eq.k_N - eq.pR_N - m - muR + s).*eq.qR_N + (w - m).*eq.qM_N ...
          + (theta.^2.*eq.qR_N.^2)./(2*c) - pc.*((e0 - gamma.*eq.k_N).*(alpha - beta).*(eq.pM_N + eq.pR_N) - G);

% ---------- 2. Biform (cooperative) game ----------
N_M_C = c.^2.*(8*alpha.^2.*(s - w - muM) - 4*alpha.*beta.*(m + muR + e0.*pc - s) + 4*beta.^2.*(m + e0.*pc - w)) ...
      + c.*( alpha.^3.*(8*gamma.^2.*pc.^2.*(muM - s + w) + 2*gamma.*pc.*theta.*(4*muM - muR - 3*s + 4*w - m) - 2*theta.^2.*(m - 2*muM + muR + s - 2*w) - 2*e0.*pc.*theta.*(gamma.*pc + theta)) ...
      + alpha.^2.*beta.*(16*gamma.^2.*pc.^2.*(-muM + s - w) + 2*gamma.*pc.*theta.*(-6*muM + 2*muR + 3*m - 7*w + 4*s) + 2*theta.^2.*(2*m - 2*muM + muR + s - 3*w) + 2*e0.*pc.*theta.*(3*gamma.*pc + 2*theta)) ...
      + alpha.*beta.^2.*(8*gamma.^2.*pc.^2.*(muM - s + w) + 2*gamma.*pc.*theta.*(2*muM - muR - 3*m - s + 4*w) + 2*theta.^2.*(muM - muR - 2*m + 2*w) - 2*e0.*pc.*theta.*(3*gamma.*pc + 2*theta)) ...
      + beta.^3.*(2*gamma.*pc.*theta.*(m - w) + 2*theta.^2.*(m - w) + 2*e0.*pc.*theta.*(gamma.*pc + theta)) );

N_R_C = c.^2.*(8*alpha.^2.*(s - m - muR - e0.*pc) + 4*alpha.*beta.*(2*m - muM + s - 3*w + 2*e0.*pc)) ...
      + c.*( alpha.^3.*(4*e0.*gamma.*pc.^2.*theta + 2*e0.*pc.*theta.^2 + 8*gamma.^2.*pc.^2.*(-muM + s - w) + 2*gamma.*pc.*theta.*(2*m - 3*muM + 2*muR + s - 3*w) + 2*theta.^2.*(m - muM + muR - w)) ...
      + alpha.^2.*beta.*(-2*e0.*pc.*theta.*(4*gamma.*pc + 3*theta) + 16*gamma.^2.*pc.^2.*(muM - s + w) + 4*gamma.*pc.*theta.*(3*muM - muR - 2*m - 2*s + 4*w) + 2*theta.^2.*(-3*m + 3*muM - 2*muR - s + 4*w)) ...
      + alpha.*beta.^2.*(4*e0.*pc.*theta.*(gamma.*pc + theta) + 8*gamma.^2.*pc.^2.*(-muM + s - w) + 2*gamma.*pc.*theta.*(-3*muM + 3*s + 2*m - 5*w) + 2*theta.^2.*(2*m - muM + s - 3*w)) );

D_C = alpha.^4.*(4*gamma.^3.*pc.^3.*theta + 5*gamma.^2.*pc.^2.*theta.^2 + 4*gamma.*pc.*theta.^3 + theta.^4) ...
    + alpha.^3.*beta.*(-8*gamma.^3.*pc.^3.*theta - 12*gamma.^2.*pc.^2.*theta.^2 - 8*gamma.*pc.*theta.^3 - 2*theta.^4) + 2*alpha.^2.*beta.^2.*gamma.^2.*pc.^2.*theta.^2 ...
    + alpha.^3.*c.*(-16*gamma.^2.*pc.^2 - 24*gamma.*pc.*theta - 12*theta.^2) + alpha.^2.*beta.*c.*(24*gamma.^2.*pc.^2 + 24*gamma.*pc.*theta + 12*theta.^2) + 16*alpha.^2.*c.^2 ...
    + alpha.*beta.^3.*(8*gamma.^3.*pc.^3.*theta + 12*gamma.^2.*pc.^2.*theta.^2 + 8*gamma.*pc.*theta.^3 + 2*theta.^4) + alpha.*beta.^2.*c.*theta.*(8*gamma.*pc + 4*theta) ...
    - beta.^4.*(4*gamma.^3.*pc.^3.*theta + 7*gamma.^2.*pc.^2.*theta.^2 + 4*gamma.*pc.*theta.^3 + theta.^4) - beta.^3.*c.*(8*gamma.^2.*pc.^2 + 8*gamma.*pc.*theta + 4*theta.^2) - 4*beta.^2.*c.^2;

eq.pM_C = N_M_C ./ D_C;
eq.pR_C = N_R_C ./ D_C;

eq.qM_C = alpha.*eq.pM_C - beta.*eq.pR_C;
eq.qR_C = alpha.*eq.pR_C - beta.*eq.pM_C;
eq.k_C  = ((theta + pc.*gamma).*(alpha - beta).*(eq.pM_C + eq.pR_C)) ./ c;
eq.n_C  = (2.*eq.qR_C.^2 + 2.*eq.qM_C.*eq.qR_C - eq.qM_C.^2) ./ (2 .* (eq.qM_C + eq.qR_C).^2);

eq.phi_M = (s - eq.pM_C - w - muM).*eq.qM_C + (theta.^2.*eq.qM_C.*(eq.qM_C + 2.*eq.qR_C)) ./ (4*c);
eq.phi_R = (s - eq.pR_C - m - muR).*eq.qR_C + (w - m).*eq.qM_C ...
         + (theta.^2.*(eq.qR_C.^2 + (eq.qM_C + eq.qR_C).^2)) ./ (4*c) ...
         - pc.*e0.*(eq.qM_C + eq.qR_C) + (pc.*gamma./(4*c)).*(eq.qM_C + eq.qR_C).^2 .* (theta + pc.*gamma) + pc.*G;
end
